#!/usr/bin/env node
/**
 * Write a dev .env file pointing at the files produced by
 * `npm run dev:gen-ca`. Generates random JWT + admin secrets.
 *
 * Re-run with --force to overwrite an existing .env.
 *
 * Dev-only. Production wires CA/QR file paths from a secret manager mount.
 */
const fs = require('node:fs');
const path = require('node:path');
const { randomBytes } = require('node:crypto');

const root = path.resolve(__dirname, '..');
const devCa = path.join(root, 'dev-ca');
const envPath = path.join(root, '.env');
const force = process.argv.includes('--force');

if (fs.existsSync(envPath) && !force) {
  console.error(`${envPath} already exists. Re-run with --force to overwrite.`);
  process.exit(1);
}

const required = [
  'operational-ca.crt',
  'operational-ca.key',
  'attestation-root.crt',
  'qr-signing.pub',
  'qr-signing.key',
];
for (const f of required) {
  if (!fs.existsSync(path.join(devCa, f))) {
    console.error(`Missing ${devCa}/${f}. Run \`npm run dev:gen-ca\` first.`);
    process.exit(1);
  }
}

const env = `# Generated by scripts/gen-dev-env.js — dev only.
NODE_ENV=development
HTTP_PORT=3000

ADMIN_API_TOKEN=${randomBytes(24).toString('base64url')}

JWT_ACCESS_SECRET=${randomBytes(48).toString('base64')}
JWT_REFRESH_SECRET=${randomBytes(48).toString('base64')}
JWT_ACCESS_TTL_SECONDS=900
JWT_REFRESH_TTL_SECONDS=2592000

DATABASE_URL=postgresql://koi:koi_dev_password@localhost:5433/koi?schema=public

REDIS_URL=redis://localhost:6379

MQTT_URL=mqtt://localhost:1883
MQTT_USERNAME=
MQTT_PASSWORD=
MQTT_TELEMETRY_TOPIC=koi/+/telemetry

OPEN_METEO_BASE_URL=https://api.open-meteo.com/v1/forecast

FCM_PROJECT_ID=
FCM_CLIENT_EMAIL=
FCM_PRIVATE_KEY=

CA_OPERATIONAL_CERT_FILE=./dev-ca/operational-ca.crt
CA_OPERATIONAL_KEY_FILE=./dev-ca/operational-ca.key
CA_ATTESTATION_CERT_FILE=./dev-ca/attestation-root.crt
CA_OPERATIONAL_CERT_DAYS=365

QR_SIGNING_PUBLIC_KEY_FILE=./dev-ca/qr-signing.pub
QR_SIGNING_PRIVATE_KEY_FILE=./dev-ca/qr-signing.key

CLAIM_TOKEN_TTL_DAYS=30
PENDING_CSR_TTL_SECONDS=600
`;

fs.writeFileSync(envPath, env, { mode: 0o600 });
console.log(`Wrote ${envPath}`);
